preset: psr2

enabled:
  - align_phpdoc
  - align_double_arrow
  - align_equals
  - blank_line_before_return
  - cast_spaces
  - concat_with_spaces
  - lowercase_static_reference
  - method_separation
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_namespace_whitespace
  - no_null_property_initialization
  - no_unneeded_final_method
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - object_operator_without_whitespace
  - ordered_class_elements
  - php_unit_construct
  - php_unit_dedicate_assert
  - php_unit_dedicate_assert_internal_type
  - php_unit_expectation
  - php_unit_no_expectation_annotation
  - php_unit_set_up_tear_down_visibility
  - phpdoc_link_to_see
  - phpdoc_no_package
  - phpdoc_order
  - property_separation
  - return_type_declaration
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - space_after_semicolon
  - ternary_operator_spaces
  - ternary_to_null_coalescing
  - yoda_style
